from ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING

BUN_NAME = "black bun"
BUN_PRICE = 100

SAUCE_TYPE = INGREDIENT_TYPE_SAUCE
SAUCE_NAME = "hot sauce"
SAUCE_PRICE = 100

FILLING_TYPE = INGREDIENT_TYPE_FILLING
FILLING_NAME = "cutlet"
FILLING_PRICE = 100

SECOND_SAUCE_NAME = "sour cream"
SECOND_SAUCE_PRICE = 200

MOVED_INGREDIENT_NAMES_FROM_FIRST_TO_LAST = [
    FILLING_NAME,
    SECOND_SAUCE_NAME,
    SAUCE_NAME,
]

MOVED_INGREDIENT_NAMES_FROM_LAST_TO_FIRST = [
    SECOND_SAUCE_NAME,
    SAUCE_NAME,
    FILLING_NAME,
]